#Hugo Config file
#Local version
#2015-11-29

# hostname (and path) to the root eg. http://spf13.com/
baseurl = "http://127.0.0.1/"

# Site title
title = "Secret Chipmunk"

# Copyright
copyright = "(c) 2015 Ron Parker"

# Language
languageCode = "en-EN"

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "yaml"

# Theme to use (located in /themes/THEMENAME/)
theme = "hyde-y"

# Pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
disqusShortname = "secretchipmunk"

[permalinks]
    #post = "/:year/:month/:day/:slug/"
    post = "/blog/:year/:month/:day/:title/"
    code = "/:slug/"

[taxonomies]
    topic = "topics"

[author]
    name = "Ron Parker"
    email = "scmunk@secretchipmunk.com"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # You can use markdown here.
    brand = "Secret Chipmunk"
    topline = "Enterprise Architecture and Security"
    footline = ""

    # Sidebar position
    # false, true, "left", "right"
    sidebar = "left"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "Home"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"


    # Google Analytics.
    googleAnalytics = "Your Google Analytics tracking code"

    # Sidebar social links.
    github = "" # Your Github profile ID
    bitbucket = "" # Your Bitbucket profile ID
    linkedin = "" # Your LinkedIn profile ID (from public URL)
    googleplus = "" # Your Google+ profile ID
    facebook = "" # Your Facebook profile ID
    twitter = "scmunk" # Your Twitter profile ID
    youtube = ""  # Your Youtube channel ID
    flattr = ""  # populate with your flattr uid

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []
